name: Build and Push Base image

on:
  push:
    branches:
      - master
    tags:
      - v*
  schedule:
    - cron: "0 */6 * * *"
    


jobs:
  BuildBase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: token
          password: ${{ secrets.GH_TOKEN }}
      - name: Build Base images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.base
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7
          push: true
          tags: ghcr.io/amirulandalib/megarestbase:latest
